# Generated by Django 4.2.17 on 2025-02-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_businesses', '0005_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pet_businesse',
            new_name='pet_business',
        ),
    ]
